### ISSUE TITLE
Scanned with virustotal.com and got positive for trojan

### ISSUE THREAD

**Issue by dthelin0906** [notagain/Tools#1]
You have many great and useful tools here that are clean but a few of them are heavy on the viruses.  When looking for tools for a new project I always use virustotal to scan my files.  I will place a link to the results of one of your files if you want to take a look.  I have a new zip archive of files that I think are safe.  Although I am not sure which files are needed for each tool I have deleted the infected files off my computer, hopefully most of the tools will still work. 
Master zip
https://www.virustotal.com/en/file/32f2befba3aa5e23a0adbee6ab03a846ac7eb725e705ad531a445143c2402935/analysis/1403632075/
MyDbcEditor.exe
https://www.virustotal.com/en/file/4c321305f67478ef9470dfac211d9cce1a5b1f78ffd7e258f8a5b50d41bc6658/analysis/

**Comment by n0t49a1n** [comment]
not a virus check again
anyway got all from new source
