### ISSUE TITLE
MyDBCEditor Does not export float values correctly

### ISSUE THREAD

**Issue by Jakobud** [notagain/Tools#2]
I opened the WorldMapArea.dbc file for a vanilla client and got data rows like this:

```
81, 1, 406, StoneTalonMountains, 3234.833, -1637.499, 2916.666, -339.583
```

When I choose export table as SQL, I get output of SQL values like this:

```
...
INSERT INTO `test` (`ID`,`field1`,`field2`,`field3`,`field4`,`field5`,`field6`,`field7`) VALUES 
('81','1','406','StonetalonMountains','1162534229','-993218561','1161185962','-1012282710'),
...
```

You can see that the positional coordinate values that are floats when viewed in the editor are being exported as large INTs. Not sure if this is a bug or if there is supposed to be some correlation there...

**Comment by thar0x29a** [comment]
Im sorry to hear so ^^

**Comment by n0t49a1n** [comment]
sorry bud  alot of these tools are discontinued
